---
- name: Cloning repository.
  sudo: no
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"

- name: Installing dotfiles.
  command: sh {{ dotfiles_install_script }}
  args:
    chdir: "{{ dotfiles_dest }}"
